import { createZip } from './zip.mjs';

const TOOL_NAME = /^[a-z][a-z0-9_]{0,63}$/;

function safeProjectName(value) {
  const name = String(value || 'generated-webmcp')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return name || 'generated-webmcp';
}

function assertTool(tool, index) {
  if (!tool || typeof tool !== 'object') throw new Error(`Tool ${index + 1} is invalid.`);
  if (!TOOL_NAME.test(tool.name || '')) throw new Error(`Tool name “${tool.name}” is invalid.`);
  if (typeof tool.description !== 'string' || tool.description.length < 8 || tool.description.length > 600) {
    throw new Error(`Tool ${tool.name} needs a description between 8 and 600 characters.`);
  }
  if (!tool.inputSchema || tool.inputSchema.type !== 'object') throw new Error(`Tool ${tool.name} needs an object input schema.`);
  if (!['read', 'write', 'consequential'].includes(tool.risk)) throw new Error(`Tool ${tool.name} has an invalid risk.`);
  if (!tool.executor || typeof tool.executor.type !== 'string') throw new Error(`Tool ${tool.name} has no executor.`);
}

function normalizeOwnerBundle(value) {
  if (value == null) return null;
  if (!value || typeof value !== 'object') throw new Error('ownerBundle must be an object.');

  const html = String(value.html || '');
  if (!html.trim()) throw new Error('ownerBundle.html is empty.');
  if (Buffer.byteLength(html) > 1_200_000) throw new Error('ownerBundle.html exceeds 1.2 MB.');

  const rawFiles = value.files && typeof value.files === 'object' && !Array.isArray(value.files) ? value.files : {};
  const entries = Object.entries(rawFiles);
  if (entries.length > 8) throw new Error('ownerBundle may contain at most eight support files.');

  const files = {};
  let totalBytes = Buffer.byteLength(html);
  for (const [name, content] of entries) {
    if (!/^[a-zA-Z0-9][a-zA-Z0-9._/-]{0,119}$/.test(name) || name.includes('..') || name.startsWith('/')) {
      throw new Error(`Unsafe ownerBundle file name: ${name}.`);
    }
    const text = String(content);
    totalBytes += Buffer.byteLength(text);
    if (totalBytes > 1_800_000) throw new Error('ownerBundle exceeds 1.8 MB.');
    files[name] = text;
  }

  return { html, files };
}

export function validateExportRequest(input) {
  if (!input || typeof input !== 'object') throw new Error('Export payload must be an object.');
  const projectName = safeProjectName(input.projectName);
  const tools = Array.isArray(input.tools) ? input.tools : [];
  if (!tools.length) throw new Error('Generate at least one tool before exporting.');
  if (tools.length > 25) throw new Error('An export may contain at most 25 tools.');
  tools.forEach(assertTool);
  const names = new Set(tools.map((tool) => tool.name));
  if (names.size !== tools.length) throw new Error('Tool names must be unique.');
  return {
    projectName,
    tools: structuredClone(tools),
    target: input.target && typeof input.target === 'object' ? structuredClone(input.target) : {},
    goal: String(input.goal || ''),
    mode: input.mode === 'browser_mcp' ? 'browser_mcp' : 'native',
    ownerBundle: normalizeOwnerBundle(input.ownerBundle),
  };
}

function jsJson(value) {
  return JSON.stringify(value, null, 2).replace(/[\u2028\u2029]/g, (character) => `\\u${character.charCodeAt(0).toString(16)}`);
}

function generatedRuntime(tools) {
  return `/**
 * Generated by MetaWebMCP.
 * Review selectors, side effects, authentication, and authorization before production use.
 */

const TOOL_SPECS = ${jsJson(tools)};
const controllers = [];

function compactVisibleText(root = document.body) {
  return (root?.innerText || root?.textContent || '')
    .replace(/\\s+/g, ' ')
    .trim()
    .slice(0, 4000);
}

function normalizedText(value) {
  return String(value || '').replace(/\\s+/g, ' ').trim().toLowerCase();
}

function elementNames(element) {
  const labelledBy = (element.getAttribute('aria-labelledby') || '')
    .split(/\\s+/)
    .filter(Boolean)
    .map((id) => document.getElementById(id)?.textContent || '')
    .join(' ');
  const labels = element.labels ? [...element.labels].map((label) => label.textContent || '').join(' ') : '';
  const values = [
    element.getAttribute('aria-label'),
    labelledBy,
    labels,
    element.getAttribute('placeholder'),
    element.getAttribute('alt'),
    element.getAttribute('title'),
    element.getAttribute('data-item'),
    element.getAttribute('name'),
    element instanceof HTMLInputElement && ['button', 'submit'].includes(element.type) ? element.value : '',
    element.innerText,
    element.textContent,
  ];
  return [...new Set(values.map(normalizedText).filter(Boolean))];
}

function findNamedElement(selector, label, root = document, allowSingle = true) {
  const candidates = [...root.querySelectorAll(selector)].filter((element) => !element.disabled);
  const expected = normalizedText(label);
  const exact = candidates.find((element) => elementNames(element).includes(expected));
  if (exact) return exact;
  const partial = candidates.find((element) => elementNames(element).some(
    (name) => name.includes(expected) || (name.length >= 4 && expected.includes(name)),
  ));
  if (partial) return partial;
  return allowSingle && candidates.length === 1 ? candidates[0] : null;
}

function setControlValue(control, value) {
  if (!control) throw new Error('Generated selector did not resolve to a form control.');
  if (control instanceof HTMLInputElement && control.type === 'checkbox') {
    control.checked = Boolean(value);
  } else if (control instanceof HTMLSelectElement) {
    const requested = (Array.isArray(value) ? value : [value]).map(normalizedText);
    let matches = 0;
    [...control.options].forEach((option) => {
      option.selected = requested.includes(normalizedText(option.value)) || requested.includes(normalizedText(option.textContent));
      if (option.selected) matches += 1;
    });
    if (!matches) throw new Error('Generated select value did not match an available option.');
  } else {
    const prototype = control instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set;
    if (setter) setter.call(control, value == null ? '' : String(value));
    else control.value = value == null ? '' : String(value);
  }
  control.dispatchEvent(new Event('input', { bubbles: true }));
  control.dispatchEvent(new Event('change', { bubbles: true }));
}

function renderRecipeValue(value, input) {
  if (typeof value === 'string') {
    return value.replace(/\\{\\{([a-zA-Z0-9_]+)\\}\\}/g, (_, key) => {
      if (!Object.hasOwn(input, key)) throw new Error(\`Generated recipe requires input “\${key}”.\`);
      return String(input[key]);
    });
  }
  if (Array.isArray(value)) return value.map((item) => renderRecipeValue(item, input));
  if (value && typeof value === 'object') {
    if (Object.hasOwn(value, '$pick')) {
      if (typeof value.$pick !== 'string' || !value.cases || typeof value.cases !== 'object') {
        throw new Error('Generated recipe contains an invalid input mapping.');
      }
      const selected = String(input[value.$pick]);
      if (!Object.hasOwn(value.cases, selected)) throw new Error(\`Generated recipe does not recognize \${value.$pick}=\${selected}.\`);
      return renderRecipeValue(value.cases[selected], input);
    }
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, renderRecipeValue(item, input)]));
  }
  return value;
}

function findItemAction(spec, input, args) {
  const selected = String(input.item ?? input.item_id ?? '');
  if (!selected) return null;
  const evidence = (spec.evidence || []).find((item) => String(item.item ?? item.itemId ?? '') === selected);
  if (!evidence) return null;
  const itemSelector = '[data-item], img[alt], [aria-label], a, h1, h2, h3, h4, h5, h6';
  const itemNodes = [...document.querySelectorAll(itemSelector)];
  const anchor = itemNodes.find((element) => elementNames(element).includes(normalizedText(selected)));
  if (!anchor) return null;
  const actionLabel = evidence.label || spec.title || args.element;
  const knownItems = [...new Set((spec.evidence || []).map((item) => String(item.item ?? item.itemId ?? '')).filter(Boolean))];
  for (let container = anchor; container && container !== document.documentElement; container = container.parentElement) {
    const scopedNodes = [...container.querySelectorAll(itemSelector)];
    const scopedItems = knownItems.filter((item) => scopedNodes.some(
      (element) => elementNames(element).includes(normalizedText(item)),
    ));
    if (scopedItems.length > 1) return null;
    const actions = [...container.querySelectorAll('button, input[type="button"], input[type="submit"], [role="button"]')]
      .filter((element) => elementNames(element).includes(normalizedText(actionLabel)));
    if (actions.length === 1) return actions[0];
    if (actions.length > 1) return null;
  }
  return null;
}

async function executeOwnedPageRecipe(spec, input) {
  const steps = spec.executor?.steps;
  if (!Array.isArray(steps) || steps.length < 1 || steps.length > 12) throw new Error('Generated browser recipe is invalid.');
  for (const step of steps) {
    const args = renderRecipeValue(step.arguments || {}, input);
    if (step.tool === 'browser_type') {
      const control = findNamedElement('input:not([type="hidden"]), textarea, [contenteditable="true"]', args.element);
      if (!control) throw new Error(\`Editable control not found: \${args.element}.\`);
      if (control instanceof HTMLElement && control.isContentEditable) {
        control.textContent = args.text == null ? '' : String(args.text);
        control.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: String(args.text || '') }));
      } else {
        setControlValue(control, args.text);
      }
    } else if (step.tool === 'browser_select_option') {
      const control = findNamedElement('select', args.element);
      if (!(control instanceof HTMLSelectElement)) throw new Error(\`Select control not found: \${args.element}.\`);
      setControlValue(control, Array.isArray(args.values) ? args.values : [args.values]);
    } else if (step.tool === 'browser_click') {
      const selectedItem = String(input.item ?? input.item_id ?? '');
      const itemScoped = selectedItem && (spec.evidence || []).some(
        (item) => String(item.item ?? item.itemId ?? '') === selectedItem,
      );
      const action = itemScoped
        ? findItemAction(spec, input, args)
        : findNamedElement('button, input[type="button"], input[type="submit"], [role="button"], a', args.element);
      if (itemScoped && !action) throw new Error(\`Action control for item \${selectedItem} was not found.\`);
      if (!(action instanceof HTMLElement)) throw new Error(\`Action control not found: \${args.element}.\`);
      action.click();
    } else if (step.tool !== 'browser_snapshot') {
      throw new Error(\`Browser step \${step.tool} needs an application-specific implementation before deployment.\`);
    }
    await new Promise((resolve) => setTimeout(resolve, 80));
  }
  return resultFor(spec, document.querySelector('[aria-live], [role="status"], main') || document.body);
}

function resultFor(spec, root = document.body) {
  return {
    ok: true,
    tool: spec.name,
    title: document.title,
    url: location.href,
    visibleState: compactVisibleText(root),
  };
}

async function executeDomSpec(spec, input) {
  const executor = spec.executor;
  if (executor.type === 'dom-form') {
    const form = document.querySelector(executor.formSelector);
    if (!(form instanceof HTMLFormElement)) throw new Error(\`Form not found: \${executor.formSelector}\`);
    for (const field of executor.fields || []) {
      if (!(field.name in input)) continue;
      const control = form.querySelector(field.selector) || document.querySelector(field.selector);
      setControlValue(control, input[field.name]);
    }
    const submit = document.querySelector(executor.submitSelector) || form.querySelector(executor.submitSelector);
    if (submit instanceof HTMLElement) submit.click();
    else if (typeof form.requestSubmit === 'function') form.requestSubmit();
    else form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await new Promise((resolve) => setTimeout(resolve, 80));
    return resultFor(spec, document.querySelector(executor.resultSelector) || document.body);
  }

  if (executor.type === 'dom-action-group') {
    const candidates = [...document.querySelectorAll(executor.selector)];
    const target = candidates.find((element) => element.getAttribute(executor.itemAttribute) === String(input.item_id));
    if (!(target instanceof HTMLElement)) throw new Error(\`No action target matched item_id=\${input.item_id}.\`);
    target.click();
    await new Promise((resolve) => setTimeout(resolve, 50));
    return resultFor(spec, document.querySelector(executor.statusSelector) || document.body);
  }

  if (executor.type === 'dom-button') {
    const button = document.querySelector(executor.selector);
    if (!(button instanceof HTMLElement)) throw new Error(\`Button not found: \${executor.selector}\`);
    button.click();
    await new Promise((resolve) => setTimeout(resolve, 50));
    return resultFor(spec, document.querySelector(executor.statusSelector) || document.body);
  }

  if (executor.type === 'dom-read') {
    const region = document.querySelector(executor.selector);
    if (!region) throw new Error(\`Readable region not found: \${executor.selector}\`);
    return resultFor(spec, region);
  }

  if (executor.type === 'mcp-recipe') {
    if (window.MetaWebMCPBrowserBridge?.execute) return window.MetaWebMCPBrowserBridge.execute(spec, input);
    return executeOwnedPageRecipe(spec, input);
  }

  throw new Error(\`Unsupported generated executor: \${executor.type}\`);
}

export async function registerGeneratedWebMCP() {
  if (typeof document.modelContext?.registerTool !== 'function') {
    console.info('WebMCP is not available. The normal website UI remains functional.');
    return { registered: [], supported: false };
  }

  for (const spec of TOOL_SPECS) {
    const controller = new AbortController();
    controllers.push(controller);
    await document.modelContext.registerTool({
      name: spec.name,
      description: spec.description,
      inputSchema: spec.inputSchema,
      annotations: {
        readOnlyHint: spec.risk === 'read',
        untrustedContentHint: true,
      },
      execute: async (input) => executeDomSpec(spec, input || {}),
    }, { signal: controller.signal });
  }

  return { registered: TOOL_SPECS.map((tool) => tool.name), supported: true };
}

export function unregisterGeneratedWebMCP() {
  controllers.splice(0).forEach((controller) => controller.abort());
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => registerGeneratedWebMCP(), { once: true });
} else {
  registerGeneratedWebMCP();
}
`;
}

function integrationHtml(projectName, target, tools) {
  const cards = tools
    .map((tool) => `<article><code>${tool.name}</code><p>${escapeHtml(tool.description)}</p><small>${tool.risk}</small></article>`)
    .join('\n');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(projectName)} · WebMCP integration pack</title>
  <style>
    :root { color-scheme: dark; font: 16px/1.5 system-ui, sans-serif; background:#0d0f10; color:#eeeae1; }
    body { max-width: 920px; margin: 0 auto; padding: 64px 24px; }
    header { border-bottom: 1px solid #34383a; padding-bottom: 28px; margin-bottom: 28px; }
    h1 { font-size: clamp(2rem, 6vw, 4.8rem); letter-spacing:-.06em; margin:0 0 12px; }
    .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:12px; }
    article { border:1px solid #34383a; border-radius:14px; padding:18px; background:#151819; }
    code { color:#d9ff67; } small { text-transform:uppercase; letter-spacing:.12em; color:#a7adaf; }
  </style>
</head>
<body>
  <header><p>Generated WebMCP integration</p><h1>${escapeHtml(projectName)}</h1><p>Target: ${escapeHtml(target.url || target.title || 'current site')}</p></header>
  <main><h2>Generated tools</h2><div class="grid">${cards}</div><p>Copy <code>src/webmcp.generated.js</code> into the target application and import it from the top-level page.</p></main>
</body>
</html>`;
}

function installGeneratedModule(html) {
  const moduleTag = '<script type="module" src="./src/webmcp.generated.js"></script>';
  if (/<\/body\s*>/i.test(html)) return html.replace(/<\/body\s*>/i, `  ${moduleTag}\n</body>`);
  return `${html}\n${moduleTag}\n`;
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
}

function readme({ projectName, target, goal, tools, mode, ownerBundle }) {
  const table = tools.map((tool) => `| \`${tool.name}\` | ${tool.risk} | ${tool.description.replaceAll('|', '\\|')} |`).join('\n');
  return `# ${projectName}

Generated by **MetaWebMCP** from an evidence-backed capability scan.

- Target: ${target.url || target.title || 'current application'}
- Goal: ${goal || 'Expose the selected website workflows to agents.'}
- Export mode: ${mode}

## Tools

| Tool | Risk | Purpose |
|---|---|---|
${table}

## Install in an owned site

1. Copy \`src/webmcp.generated.js\` into the target application's public or source directory.
2. Import it from the **top-level page** after the existing application logic is available.
3. Review every selector and connect the executor to existing application functions where possible. Calling stable application functions is preferable to DOM actuation.
4. Preserve the site's normal authentication, authorization, validation, and confirmation behavior.
5. Test in ChatGPT's in-app browser or Chrome with WebMCP testing enabled.

Example:

\`\`\`html
<script type="module" src="/webmcp.generated.js"></script>
\`\`\`

## Important review points

- Tool metadata and target-page output are untrusted content.
- \`readOnlyHint\` is generated from the inferred risk and must be reviewed.
- Write and consequential actions require human review before deployment.
- DOM selectors are a compatibility layer. Replace them with existing client-side functions for production reliability.
- Browser-derived recipes use narrow accessible-name and item-context lookups when installed in the owned target page; replace these compatibility lookups with stable application functions where source access permits.
${mode === 'browser_mcp' ? '- The exported tools execute on the owned page without MetaWebMCP or a browser service. An explicit `window.MetaWebMCPBrowserBridge` remains supported for isolated remote execution.' : ''}

## Local inspection

\`\`\`bash
node serve.mjs
# open http://localhost:4173
\`\`\`

${ownerBundle
    ? 'This repository includes the supplied target UI with the generated module installed, so the local page is an executable preview. It remains a generated compatibility layer and still requires source-level review before production use.'
    : 'The local page is an integration report because the original target source was not bundled. Install the generated module inside the actual target application before executing its tools.'}
`;
}

function agentInstructions({ target, goal, tools }) {
  return `# AGENTS.md

## Objective

Install and harden the generated WebMCP integration for ${target.url || target.title || 'the current application'}.

User goal: ${goal || 'Expose selected workflows to agents.'}

## Required approach

- Trace each generated tool to the existing application handler, store, API client, and permission gate.
- Replace DOM clicks with stable application functions wherever source access permits.
- Do not weaken authentication, authorization, validation, CSRF protection, confirmations, or audit logging.
- Keep the existing human interface functional when WebMCP is unavailable.
- Keep tool inputs narrow and outputs sufficient to verify state changes.
- Add tests for tool selection, arguments, execution, and visible postconditions.

## Generated tools

${tools.map((tool) => `- \`${tool.name}\` (${tool.risk}): ${tool.description}`).join('\n')}
`;
}

function manualEvals(tools) {
  return `# Manual evaluation plan

Run these checks in a browser with WebMCP enabled.

${tools
  .map(
    (tool, index) => `## ${index + 1}. \`${tool.name}\`

- Intent prompt: ask the agent to accomplish “${tool.title || tool.name}” without naming the tool.
- Expected selection: \`${tool.name}\`.
- Sample arguments: \`${JSON.stringify(tool.sampleArgs || {})}\`.
- Verify input validation rejects unknown or malformed fields.
- Verify the normal page UI reflects the result.
- Risk classification: **${tool.risk}**. ${tool.risk === 'read' ? 'Confirm it does not mutate state.' : 'Confirm the user receives the normal review or confirmation boundary.'}
`,
  )
  .join('\n')}
`;
}

export function generateProjectFiles(rawInput) {
  const input = validateExportRequest(rawInput);
  const metadata = {
    generatedAt: new Date().toISOString(),
    generator: 'MetaWebMCP 1.0.0',
    target: input.target,
    goal: input.goal,
    mode: input.mode,
    tools: input.tools,
    runnablePreview: Boolean(input.ownerBundle),
  };

  const files = {
    'README.md': readme(input),
    'AGENTS.md': agentInstructions(input),
    'LICENSE': `MIT License\n\nCopyright (c) 2026 ${input.projectName} contributors\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.\n`,
    'package.json': `${JSON.stringify({ name: input.projectName, version: '1.0.0', private: true, type: 'module', scripts: { start: 'node serve.mjs' }, license: 'MIT' }, null, 2)}\n`,
    'serve.mjs': `import http from 'node:http';\nimport { readFile } from 'node:fs/promises';\nimport path from 'node:path';\nconst root = new URL('.', import.meta.url);\nconst types = { '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.css':'text/css; charset=utf-8', '.json':'application/json; charset=utf-8', '.md':'text/markdown; charset=utf-8' };\nhttp.createServer(async (req,res) => { try { const pathname = new URL(req.url, 'http://local').pathname; const file = pathname === '/' ? 'index.html' : pathname.slice(1); const full = new URL(file, root); if (!full.href.startsWith(root.href)) throw new Error('bad path'); const data = await readFile(full); res.writeHead(200, {'content-type': types[path.extname(file)] || 'application/octet-stream', 'x-content-type-options':'nosniff'}); res.end(data); } catch { res.writeHead(404); res.end('Not found'); } }).listen(4173, () => console.log('http://localhost:4173'));\n`,
    'index.html': input.ownerBundle ? installGeneratedModule(input.ownerBundle.html) : integrationHtml(input.projectName, input.target, input.tools),
    'integration-report.html': integrationHtml(input.projectName, input.target, input.tools),
    ...(input.ownerBundle?.files || {}),
    'src/webmcp.generated.js': generatedRuntime(input.tools),
    'src/tool-spec.json': `${jsJson(input.tools)}\n`,
    'metawebmcp-report.json': `${jsJson(metadata)}\n`,
    'tests/manual-evals.md': manualEvals(input.tools),
  };
  return { ...input, files };
}

export function generateProjectZip(input) {
  const project = generateProjectFiles(input);
  const root = `${project.projectName}/`;
  const files = Object.fromEntries(Object.entries(project.files).map(([name, content]) => [`${root}${name}`, content]));
  return {
    projectName: project.projectName,
    fileName: `${project.projectName}.zip`,
    buffer: createZip(files),
    fileCount: Object.keys(files).length,
  };
}
